services:

  agent:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spring-ai-agent
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"