package com.ecom.agent.service;

public interface ChatService {

    /**
     * Processes a user's message, interacts with the AI model, and returns the response.
     * This involves retrieving relevant chat history, calling the AI, and saving the new interaction.
     *
     * @param userId  The identifier for the current user.
     * @param message The message from the user.
     * @return The response generated by the AI.
     */
    String getAiResponse(String userId, String message);
}