name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: 168064666968.dkr.ecr.ap-south-1.amazonaws.com
      ECR_REPOSITORY: spring-ai-agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Push Docker Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=168064666968.dkr.ecr.ap-south-1.amazonaws.com/spring-ai-agent:latest

            docker pull $IMAGE

            docker stop spring-ai-agent || true
            docker rm spring-ai-agent || true

            docker run -d \
              --name spring-ai-agent \
              -p 8080:8080 \
              --restart unless-stopped \
              --env-file /home/ubuntu/agent/.env \
              $IMAGE

            docker image prune -f